version: '3.8'

networks:
  amcloud-network: 
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/gateway.conf:/etc/nginx/conf.d/gateway.conf:ro
      - ./nginx/configserver.conf:/etc/nginx/conf.d/configserver.conf:ro
      - ./nginx/iam.conf:/etc/nginx/conf.d/iam.conf:ro
      - ./nginx/platform.amcloud.cm.conf:/etc/nginx/conf.d/platform.amcloud.cm.conf:ro
      - ./certs:/etc/nginx/certs:ro 
    ports:
      - "80:80"
      - "443:443"
    networks:
      - amcloud-network
    depends_on:
      - gateway
      - configserver
      - iam

  configserver:
    image: ghcr.io/projects-in3-uds/configserver:1.0.1
    container_name: configserver
    volumes:
      - ./env/.env.config-server:/app/.env:ro
    ports:
      - "8888:8888"
    networks:
      - amcloud-network
    command: java -jar app.jar
    healthcheck: 
      test: ["CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: amcloud_admin
      POSTGRES_PASSWORD: amcloud_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - amcloud-network
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U amcloud_admin -d amcloud_reservation_db"] 
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  gateway:
    image: ghcr.io/projects-in3-uds/gateway:1.0.1
    container_name: gateway
    volumes:
     - ./env/.env.gateway:/app/.env:ro
    ports:
      - "8080:8080"
    depends_on:
      iam:
        condition: service_healthy
    networks:
      - amcloud-network
    command: java -jar app.jar
    healthcheck: 
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  iam:
    image: ghcr.io/projects-in3-uds/iam:1.0.1
    container_name: iam
    volumes:
      - ./env/.env.iam:/app/.env:ro
    ports:
      - "8081:8081"
    depends_on:
      configserver:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - amcloud-network
    command: java -jar app.jar
    healthcheck: 
      test: ["CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s

  reservation:
    image: ghcr.io/projects-in3-uds/reservation:1.0.1
    container_name: reservation
    volumes:
      - ./env/.env.reservation:/app/.env:ro
    ports:
      - "8083:8083"
    depends_on:
      configserver:
        condition: service_healthy
      postgres:
        condition: service_healthy
      iam: 
        condition: service_healthy
    networks:
      - amcloud-network
    command: java -jar app.jar
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8083/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s

  billing:
    image: ghcr.io/projects-in3-uds/billing:1.0.1
    container_name: billing
    volumes:
      - ./env/.env.billing:/app/.env:ro
    ports:
      - "8082:8082"
    depends_on:
      configserver:
        condition: service_healthy
      postgres:
        condition: service_healthy
      iam: 
        condition: service_healthy
    networks:
      - amcloud-network
    command: java -jar app.jar
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8082/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s

  notification:
    image: ghcr.io/projects-in3-uds/notification:1.0.1
    container_name: notification
    volumes:
      - ./env/.env.notification:/app/.env:ro
    ports:
      - "8085:8085"
    depends_on:
      configserver:
        condition: service_healthy
      iam: 
        condition: service_healthy
    networks:
      - amcloud-network
    command: java -jar app.jar
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8085/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s

  invitation:
    image: ghcr.io/projects-in3-uds/invitation:1.0.1
    container_name: invitation
    volumes:
      - ./env/.env.invitation:/app/.env:ro
    ports:
      - "8084:8084"
    depends_on:
      configserver:
        condition: service_healthy
      postgres:
        condition: service_healthy
      iam: 
        condition: service_healthy
    networks:
      - amcloud-network
    command: java -jar app.jar
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8084/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s

volumes:
  postgres-data:


