version: '3.8'

networks:
  amcloud-network: # Define a custom network
    driver: bridge

services:
  configserver:
    image: ghcr.io/project-in3-uds/config-server:latest
    container_name: configserver
    volumes:
      - ./env/.env.config-server:/app/.env:ro
    ports:
      - "8888:8888"
    networks:
      - amcloud-network
    command: /bin/sh -c "sleep 5 && java -jar app.jar"

  postgres:
    image: ghcr.io/project-in3-uds/postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: amcloud_admin
      POSTGRES_PASSWORD: amcloud_pass
      POSTGRES_DB1: amcloud_reservation_db
      POSTGRES_DB2: amcloud_billing_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - amcloud-network
    command: /bin/sh -c "sleep 5 && docker-entrypoint.sh postgres"

  gateway:
    image: ghcr.io/project-in3-uds/gateway:latest
    container_name: gateway
    volumes:
      - ./env/.env.gateway:/app/.env:ro
    ports:
      - "8080:8080"
    depends_on:
      - configserver
    networks:
      - amcloud-network
    command: /bin/sh -c "sleep 10 && java -jar app.jar"

  iam:
    image: ghcr.io/project-in3-uds/iam:latest
    container_name: iam
    volumes:
      - ./env/.env.iam:/app/.env:ro
    ports:
      - "8081:8081"
    depends_on:
      - configserver
      - gateway
      - postgres
    networks:
      - amcloud-network
    command: /bin/sh -c "sleep 15 && java -jar app.jar"

  reservation:
    image: ghcr.io/project-in3-uds/reservation:latest
    container_name: reservation
    volumes:
      - ./env/.env.reservation:/app/.env:ro
    ports:
      - "8083:8083"
    depends_on:
      - configserver
      - gateway
      - postgres
      - iam
    networks:
      - amcloud-network
    command: /bin/sh -c "sleep 20 && java -jar app.jar"

  billing:
    image: ghcr.io/project-in3-uds/billing:latest
    container_name: billing
    volumes:
      - ./env/.env.billing:/app/.env:ro
    ports:
      - "8082:8082"
    depends_on:
      - configserver
      - gateway
      - postgres
      - iam
    networks:
      - amcloud-network
    command: /bin/sh -c "sleep 20 && java -jar app.jar"

  notification:
    image: ghcr.io/project-in3-uds/notification:latest
    container_name: notification
    volumes:
      - ./env/.env.notification:/app/.env:ro
    ports:
      - "8085:8085"
    depends_on:
      - configserver
      - gateway
      - iam
    networks:
      - amcloud-network
    command: /bin/sh -c "sleep 25 && java -jar app.jar"

  invitation:
    image: ghcr.io/project-in3-uds/invitation:latest
    container_name: invitation
    volumes:
      - ./env/.env.invitation:/app/.env:ro
    ports:
      - "8084:8084"
    depends_on:
      - configserver
      - gateway
      - postgres
      - iam
    networks:
      - amcloud-network
    command: /bin/sh -c "sleep 25 && java -jar app.jar"

volumes:
  postgres-data:
