### Envoyer une notification via le Gateway
POST http://localhost:8080/notifications/send
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJteS1rZXktaWQiLCJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIl0sInNjb3BlcyI6WyJyZWFkIiwid3JpdGUiXSwic3ViIjoiYWRtaW4iLCJpYXQiOjE3NDg5MzU1MTQsImV4cCI6MTc0ODkzOTExNCwiaXNzIjoiaHR0cDovL2lhbTo4MDgxIn0.MBbS0XWsL4ZTCc_glCmTXm6bZwrHQAt44zwHkMQRoEEFkxXcvTJFxcQ_dDcApw5d0SGspZb70EdokHh64xJooQzOilCIQL_uOi_edKyIk7DaZ9fSHT8wrHw-jEncHa8VLYC5gmWp-Itknz1pjV1OQl2gDLVbZTidmHLjVmmx5Ls0dBbVdHIyCNbipoznDJ8bsSRfeMBxSePjwe3LhAdSKJb16BQUz4HxoH-DRSNLBrLEMaE_OxgSGy4tXpcx54pyps1GllLBZiTjKVaH853saX7llw1gQlSZ1b7Tge5oFeAt_I54qMWcyRSWnI8bj6ErYY36iv_AG3tRBKQi4Hquyw

{
  "to": "andersonmetsanoum@gmail.com",
  "subject": "Welcome",
  "content": "Welcome to AMCLOUD platform!"
}
