### Créer une réservation via Gateway
POST http://localhost:8080/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXRzYSIsImlhdCI6MTc0ODAyNzEyNSwiZXhwIjoxNzQ4MDMwNzI1fQ.O1o6mzSmKK4mQ8G56SHNR0Q1VFCKfSUwzBpsS5SV9Y0Hsv8GbeCG7QXgoXRigNHz-qpLgwls4DiKlaynQUtPDoLHIFXa4CayInT3A1302XdG829Z_IiNVaNg1SJA48FVADacVNnPuxJiKYSR2dHtlX1OO4aBUfTe_C4OtEMOEe2FilZSx4ga02K9baE6DWOnaTze-uJOX5wMDYY8DXm4KLf8FEdIMN071pIr96lugPPimag3ZPQ4nHXPEl02LedR-wrFP_9KhjqFHvP1OXgtIJ3wIjfIiWtwnUbKwcqEtYogML3_Qpyx2vxLcurBgJavkKj9aGfW1G4_b1eh5oyYlw

{
  "travelerName": "David",
  "destination": "Berlin",
  "agencyName": "AgenceDelta"
}

### Lister les réservations via Gateway
GET http://localhost:8080/reservations
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtZXRzYSIsImlhdCI6MTc0ODAyNzEyNSwiZXhwIjoxNzQ4MDMwNzI1fQ.O1o6mzSmKK4mQ8G56SHNR0Q1VFCKfSUwzBpsS5SV9Y0Hsv8GbeCG7QXgoXRigNHz-qpLgwls4DiKlaynQUtPDoLHIFXa4CayInT3A1302XdG829Z_IiNVaNg1SJA48FVADacVNnPuxJiKYSR2dHtlX1OO4aBUfTe_C4OtEMOEe2FilZSx4ga02K9baE6DWOnaTze-uJOX5wMDYY8DXm4KLf8FEdIMN071pIr96lugPPimag3ZPQ4nHXPEl02LedR-wrFP_9KhjqFHvP1OXgtIJ3wIjfIiWtwnUbKwcqEtYogML3_Qpyx2vxLcurBgJavkKj9aGfW1G4_b1eh5oyYlw
